<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Trucendoos</text>

        <Action name="pykrita_CopyPaste_Frame_Board">
        <icon></icon>
        <text>CopyPaste_Frame_Board</text>
        <whatsThis></whatsThis>
        <toolTip>First creates a storyboard scene, then pastes the copied layer to the board. Useful when re-using assets a lot.</toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>shift+F10</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>
