<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Trucendoos</text>

        <Action name="pykrita_berenvoedsel">
        <icon></icon>
        <text>berenvoedsel</text>
        <whatsThis></whatsThis>
        <toolTip>Quickly exports storyboard demos</toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>shift+F10</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>
